# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TN2KPpOuns-4bRG0xsAYkv_uBa-vy0L
"""

# ===========================
# CELL 1: Install Dependencies
# ===========================
print("📦 Installing dependencies...")

!pip install -q fastapi nest-asyncio pyngrok
!pip install -q firebase-admin
!pip install -q google-generativeai
!pip install -q numpy
!pip install -q uvicorn
!pip install -q sentence-transformers
!pip install -q torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

print("✅ All dependencies installed successfully!")
print("📌 Next: Run Cell 02 to import libraries")

# ===========================
# CELL 2: Import Libraries
# ===========================
print("📚 Importing libraries...")

import os
import json
import re
import nest_asyncio
import asyncio
from datetime import datetime
from typing import List, Dict, Optional
from pydantic import BaseModel
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import uvicorn
from pyngrok import ngrok
import google.generativeai as genai
import firebase_admin
from firebase_admin import credentials, firestore
import numpy as np
from sentence_transformers import SentenceTransformer
import time

# Allow nested async loops in Colab
nest_asyncio.apply()

print("✅ Libraries imported successfully!")
print("📌 Next: Run Cell 03 to configure settings")

# ===========================
# CELL 3: Configuration Setup
# ===========================
print("🔧 Setting up configuration...")

# ⚠️ IMPORTANT: CONFIGURE THESE BEFORE RUNNING
GEMINI_API_KEY = "AIzaSyBd9ayNnUO51zpB4JtQVDHfdw67Y4LerHc"  # Get from: https://makersuite.google.com/app/apikey
NGROK_AUTH_TOKEN = "34RuNCVR0o60Xl34SO01IPOJy0p_eu3CHpGA8gjg8sSYc1hR"  # Get from: https://dashboard.ngrok.com/get-started/your-authtoken
FIREBASE_CREDENTIALS_PATH = "/content/firebase-credentials.json"  # Upload your Firebase JSON file

# Sentence Transformer Model Selection
# Choose based on your needs:
# ┌──────────────────────────────────────────────────────────────────┐
# │ Model                                  │ Dims │ Speed │ Quality │
# ├──────────────────────────────────────────────────────────────────┤
# │ all-MiniLM-L6-v2                       │ 384  │ Fast  │ Good    │ ← Recommended
# │ all-mpnet-base-v2                      │ 768  │ Slow  │ Better  │
# │ paraphrase-multilingual-MiniLM-L12-v2  │ 384  │ Fast  │ Multi   │
# └──────────────────────────────────────────────────────────────────┘

EMBEDDING_MODEL_NAME = "all-MiniLM-L6-v2"

print(f"📊 Selected embedding model: {EMBEDDING_MODEL_NAME}")
print("⚠️  IMPORTANT: Update your API keys above before proceeding!")
print("📌 Next: Run Cell 04 to initialize Firebase")

# ===========================
# CELL 4: Initialize Firebase
# ===========================
print("🚀 Initializing Firebase...")

try:
    if not firebase_admin._apps:
        cred = credentials.Certificate(FIREBASE_CREDENTIALS_PATH)
        firebase_admin.initialize_app(cred)

    db = firestore.client()
    print("✅ Firebase initialized successfully!")
    print("📌 Next: Run Cell 05 to initialize Gemini")
except Exception as e:
    print(f"❌ Firebase initialization failed: {e}")
    print("💡 Make sure you've uploaded your Firebase credentials JSON file!")
    print("💡 Path should be:", FIREBASE_CREDENTIALS_PATH)

# ===========================
# CELL 5: Initialize Gemini
# ===========================
print("🤖 Initializing Gemini AI...")

try:
    genai.configure(api_key=GEMINI_API_KEY)
    gemini_model = genai.GenerativeModel('gemini-2.0-flash-exp')

    print("✅ Gemini initialized successfully!")
    print("💡 Gemini will ONLY be used for:")
    print("   • Intent classification")
    print("   • Response generation")
    print("   • NOT for embeddings (handled by Sentence Transformers)")
    print("📌 Next: Run Cell 06 to load Sentence Transformers")
except Exception as e:
    print(f"❌ Gemini initialization failed: {e}")
    print("💡 Check if your GEMINI_API_KEY is correct in Cell 03")

# ===========================
# CELL 6: Initialize Sentence Transformers
# ===========================
print(f"📥 Loading Sentence Transformer: {EMBEDDING_MODEL_NAME}...")
print("⏳ This may take 1-2 minutes on first run (downloading model)...")

try:
    embedding_model = SentenceTransformer(EMBEDDING_MODEL_NAME)
    embedding_dimension = embedding_model.get_sentence_embedding_dimension()

    print("\n" + "="*60)
    print("✅ Sentence Transformer loaded successfully!")
    print("="*60)
    print(f"📊 Model: {EMBEDDING_MODEL_NAME}")
    print(f"📊 Embedding dimension: {embedding_dimension}")
    print(f"💰 API Cost: $0.00 (runs locally)")
    print("⚡ All embeddings will be generated on your machine")
    print("="*60)
    print("\n📌 Next: Run Cell 07 to create embedding functions")
except Exception as e:
    print(f"❌ Failed to load Sentence Transformer: {e}")
    print("💡 Try reinstalling: !pip install -U sentence-transformers")

# ===========================
# CELL 7: Embedding Functions
# ===========================
print("🛠 Creating embedding functions...")

def generate_embedding(text: str) -> List[float]:
    """
    Generate embedding using Sentence Transformers (LOCAL - NO API CALL)

    Args:
        text: Input text to embed

    Returns:
        List of floats representing the embedding vector
    """
    try:
        embedding = embedding_model.encode(text, convert_to_tensor=False)
        return embedding.tolist()
    except Exception as e:
        print(f"Error generating embedding: {e}")
        return [0.0] * embedding_dimension

def generate_query_embedding(query: str) -> List[float]:
    """
    Generate embedding for user query (LOCAL - NO API CALL)

    Args:
        query: User's search query

    Returns:
        List of floats representing the query embedding
    """
    try:
        embedding = embedding_model.encode(query, convert_to_tensor=False)
        return embedding.tolist()
    except Exception as e:
        print(f"Error generating query embedding: {e}")
        return [0.0] * embedding_dimension

def generate_batch_embeddings(texts: List[str]) -> List[List[float]]:
    """
    Generate embeddings for multiple texts efficiently (LOCAL - NO API CALLS)

    Args:
        texts: List of texts to embed

    Returns:
        List of embedding vectors
    """
    try:
        embeddings = embedding_model.encode(
            texts,
            convert_to_tensor=False,
            show_progress_bar=True,
            batch_size=32
        )
        return [emb.tolist() for emb in embeddings]
    except Exception as e:
        print(f"Error generating batch embeddings: {e}")
        return [[0.0] * embedding_dimension for _ in texts]

print("✅ Embedding functions created!")
print(f"📊 Embedding dimension: {embedding_dimension}")
print("💡 All embeddings generated locally - zero API costs!")
print("📌 Next: Run Cell 08 to create utility functions")

# ===========================
# CELL 8: Utility Functions
# ===========================
print("🛠 Creating utility functions...")

def cosine_similarity(vec1: List[float], vec2: List[float]) -> float:
    """
    Calculate cosine similarity between two vectors

    Args:
        vec1: First embedding vector
        vec2: Second embedding vector

    Returns:
        Similarity score between 0 and 1 (1 = identical)
    """
    vec1 = np.array(vec1)
    vec2 = np.array(vec2)

    dot_product = np.dot(vec1, vec2)
    norm1 = np.linalg.norm(vec1)
    norm2 = np.linalg.norm(vec2)

    if norm1 == 0 or norm2 == 0:
        return 0.0

    return float(dot_product / (norm1 * norm2))

def extract_rank(query: str) -> Optional[int]:
    """
    Extract VITEEE rank from user query

    Args:
        query: User's input text

    Returns:
        Extracted rank (int) or None if not found
    """
    patterns = [
        r'rank\s+(?:is\s+)?(\d+)',
        r'got\s+(\d+)\s*rank',
        r'scored\s+(\d+)',
        r'(\d+)\s+rank',
        r'viteee\s+rank\s+(\d+)',
        r'my\s+rank\s+is\s+(\d+)',
        r'rank\s*:\s*(\d+)',
        r'(\d{4,6})',  # 4-6 digit numbers
    ]

    query_lower = query.lower()

    for pattern in patterns:
        match = re.search(pattern, query_lower)
        if match:
            rank = int(match.group(1))
            # Validate rank is within reasonable range
            if 1 <= rank <= 200000:
                return rank

    return None

print("✅ Utility functions created!")
print("📌 Next: Run Cell 09 to create Firebase service class")

# ===========================
# CELL 9: Firebase Service Class
# ===========================
print("🗄 Setting up Firebase operations...")

class FirebaseService:
    def __init__(self):
        self.db = db
        self.faqs_collection = db.collection('vit_faqs')
        self.cutoffs_collection = db.collection('vit_cutoffs')
        self.logs_collection = db.collection('query_logs')

    def add_faq(self, faq_data: Dict) -> str:
        """Add FAQ to Firebase"""
        try:
            doc_ref = self.faqs_collection.add(faq_data)
            return doc_ref[1].id
        except Exception as e:
            print(f"Error adding FAQ: {e}")
            return None

    def add_cutoff(self, cutoff_data: Dict) -> str:
        """Add cutoff data to Firebase"""
        try:
            doc_ref = self.cutoffs_collection.add(cutoff_data)
            return doc_ref[1].id
        except Exception as e:
            print(f"Error adding cutoff: {e}")
            return None

    def vector_search_faqs(self, query_embedding: List[float], top_k: int = 3) -> List[Dict]:
        """
        Perform vector search on FAQs using cosine similarity
        Uses Sentence Transformer embeddings (no API calls)
        """
        try:
            docs = self.faqs_collection.stream()

            results = []
            for doc in docs:
                data = doc.to_dict()
                if 'embedding' in data:
                    similarity = cosine_similarity(query_embedding, data['embedding'])
                    results.append({
                        'id': doc.id,
                        'question': data.get('question', ''),
                        'answer': data.get('answer', ''),
                        'category': data.get('category', ''),
                        'score': similarity
                    })

            results.sort(key=lambda x: x['score'], reverse=True)
            return results[:top_k]

        except Exception as e:
            print(f"Error in vector search: {e}")
            return []

    def vector_search_cutoffs(self, query_embedding: List[float], top_k: int = 5) -> List[Dict]:
        """
        Perform vector search on cutoffs using cosine similarity
        Uses Sentence Transformer embeddings (no API calls)
        """
        try:
            docs = self.cutoffs_collection.stream()

            results = []
            for doc in docs:
                data = doc.to_dict()
                if 'embedding' in data:
                    similarity = cosine_similarity(query_embedding, data['embedding'])
                    results.append({
                        'id': doc.id,
                        'campus': data.get('campus', ''),
                        'branch': data.get('branch', ''),
                        'category': data.get('category', ''),
                        'rank_range': data.get('rank_range', []),
                        'answer': data.get('answer', ''),
                        'score': similarity
                    })

            results.sort(key=lambda x: x['score'], reverse=True)
            return results[:top_k]

        except Exception as e:
            print(f"Error in vector search: {e}")
            return []

    def get_cutoffs_by_rank(self, rank: int) -> List[Dict]:
        """Get cutoffs where rank falls in range"""
        try:
            docs = self.cutoffs_collection.stream()

            results = []
            for doc in docs:
                data = doc.to_dict()
                rank_range = data.get('rank_range', [])

                if len(rank_range) == 2:
                    if rank_range[0] <= rank <= rank_range[1]:
                        results.append({
                            'id': doc.id,
                            'campus': data.get('campus', ''),
                            'branch': data.get('branch', ''),
                            'category': data.get('category', ''),
                            'rank_range': rank_range,
                            'answer': data.get('answer', '')
                        })

            return results

        except Exception as e:
            print(f"Error getting cutoffs by rank: {e}")
            return []

    def log_query(self, log_data: Dict):
        """Log query for analytics"""
        try:
            log_data['timestamp'] = firestore.SERVER_TIMESTAMP
            self.logs_collection.add(log_data)
        except Exception as e:
            print(f"Error logging query: {e}")

# Initialize Firebase Service
firebase_service = FirebaseService()

print("✅ Firebase service class created!")
print("📌 Next: Run Cell 10 to create Gemini AI functions")

# ===========================
# CELL 10: Gemini AI Functions
# ===========================
print("🤖 Setting up Gemini AI functions...")

def classify_intent(query: str) -> Dict:
    """
    Classify user query intent using Gemini
    (Uses Gemini API - minimal calls)
    """
    prompt = f"""You are an intent classifier for VIT admission queries.

Analyze this query and classify it:
- "cutoff" - Questions about admission cutoffs, closing ranks
- "rank_prediction" - Student provides rank, wants eligible branches
- "faq" - Questions about hostel, FFCS, clubs, campus life, fees
- "counselling" - Questions about counselling process
- "general" - Other VIT questions

Query: "{query}"

Respond ONLY with valid JSON:
{{
    "intent": "one of the above",
    "confidence": 0.85,
    "reasoning": "brief explanation"
}}"""

    try:
        response = gemini_model.generate_content(prompt)
        result_text = response.text.strip()

        # Clean up markdown formatting
        if "```json" in result_text:
            result_text = result_text.split("```json")[1].split("```")[0].strip()
        elif "```" in result_text:
            result_text = result_text.split("```")[1].split("```")[0].strip()

        result = json.loads(result_text)
        return result

    except Exception as e:
        # Fallback classification (no API call)
        query_lower = query.lower()

        if any(word in query_lower for word in ["rank", "got", "scored"]):
            if any(char.isdigit() for char in query):
                return {"intent": "rank_prediction", "confidence": 0.7, "reasoning": "Contains rank"}

        if any(word in query_lower for word in ["cutoff", "closing rank"]):
            return {"intent": "cutoff", "confidence": 0.7, "reasoning": "About cutoffs"}

        return {"intent": "faq", "confidence": 0.6, "reasoning": "General query"}

def generate_response(query: str, context: str, intent: str) -> str:
    """
    Generate natural response using Gemini
    (Uses Gemini API - for response generation only)
    """
    if intent == "rank_prediction":
        prompt = f"""You are a friendly VIT admission assistant helping a 12th-grade student.

Student asked: "{query}"

Admission data:
{context}

Provide a helpful response (under 100 words) that:
1. Answers their question about branch eligibility
2. Mentions 2-3 realistic options
3. Keeps a positive tone
4. Suggests exploring other options

Response:"""

    elif intent == "cutoff":
        prompt = f"""You are a VIT admission assistant.

Student asked: "{query}"

Cutoff information:
{context}

Provide a clear answer (under 80 words) that:
1. Addresses their cutoff question
2. Mentions specific ranks/categories
3. Keeps a helpful tone

Response:"""

    elif intent == "faq":
        prompt = f"""You are a friendly VIT admission assistant.

Student asked: "{query}"

Information:
{context}

Provide a natural answer (under 100 words) that:
1. Directly answers the question
2. Uses simple language
3. Sounds helpful

Response:"""

    else:
        prompt = f"""Student asked: "{query}"

Context: {context}

Provide a helpful response in under 80 words."""

    try:
        response = gemini_model.generate_content(prompt)
        return response.text.strip()
    except Exception as e:
        return "I'm having trouble responding. Please try again."

print("✅ Gemini functions ready!")
print("💡 Gemini API used only for:")
print("   • Intent classification (1 call per query)")
print("   • Response generation (1 call per query)")
print("📌 Next: Run Cell 11 for rank prediction logic")

# ===========================
# CELL 11: Rank Prediction Logic
# ===========================
print("🎯 Setting up rank prediction...")

def predict_branches(rank: int, cutoffs: List[Dict]) -> List[Dict]:
    """
    Predict eligible branches with confidence levels

    Args:
        rank: Student's VITEEE rank
        cutoffs: List of cutoff data from Firebase

    Returns:
        List of predictions with confidence scores
    """
    predictions = []

    for cutoff in cutoffs:
        rank_min = cutoff["rank_range"][0]
        rank_max = cutoff["rank_range"][1]

        # Calculate position in range (0 = best, 1 = worst)
        position = (rank - rank_min) / (rank_max - rank_min) if rank_max > rank_min else 0.5

        # Determine confidence based on position
        if position <= 0.3:
            confidence = "High"
            confidence_score = 0.9
        elif position <= 0.6:
            confidence = "Good"
            confidence_score = 0.7
        elif position <= 0.85:
            confidence = "Moderate"
            confidence_score = 0.5
        else:
            confidence = "Borderline"
            confidence_score = 0.3

        predictions.append({
            "campus": cutoff["campus"],
            "branch": cutoff["branch"],
            "category": cutoff["category"],
            "rank_range": cutoff["rank_range"],
            "confidence": confidence,
            "confidence_score": confidence_score
        })

    # Sort by confidence score (best options first)
    predictions.sort(key=lambda x: x["confidence_score"], reverse=True)
    return predictions

def format_predictions_for_gemini(predictions: List[Dict], rank: int) -> str:
    """
    Format predictions as context for Gemini

    Args:
        predictions: List of branch predictions
        rank: Student's rank

    Returns:
        Formatted string for Gemini prompt
    """
    if not predictions:
        return f"No branch predictions found for rank {rank}."

    context = f"Student's VITEEE Rank: {rank}\n\nELIGIBLE BRANCHES:\n\n"

    for i, pred in enumerate(predictions[:8], 1):
        context += f"{i}. {pred['branch']} - {pred['campus']}\n"
        context += f"   Category: {pred['category']}\n"
        context += f"   Rank Range: {pred['rank_range'][0]} - {pred['rank_range'][1]}\n"
        context += f"   Admission Chance: {pred['confidence']}\n\n"

    return context

print("✅ Rank prediction logic ready!")
print("📌 Next: Run Cell 12 to create main query handler")

# ===========================
# CELL 12: Main Query Handler
# ===========================
print("🎬 Setting up main query handler...")

async def process_query(query: str, user_id: str = None) -> Dict:
    """
    Main function to process user queries

    Flow:
    1. Classify intent (Gemini API call)
    2. Generate query embedding (Local - Sentence Transformers)
    3. Vector search Firebase (Local computation)
    4. Generate response (Gemini API call)

    Args:
        query: User's question
        user_id: Optional user identifier

    Returns:
        Dict containing answer, intent, confidence, and metadata
    """

    print(f"\n🔍 Processing: {query}")

    # Step 1: Classify intent (Gemini API)
    intent_result = classify_intent(query)
    intent = intent_result["intent"]
    confidence = intent_result["confidence"]

    print(f"🎯 Intent: {intent} (confidence: {confidence})")

    # Handle low confidence
    if confidence < 0.5:
        return {
            "answer": "Could you clarify if you're asking about cutoffs, hostels, FFCS, or something else?",
            "intent": "clarification_needed",
            "confidence": confidence,
            "timestamp": datetime.utcnow().isoformat()
        }

    # Step 2: Process based on intent
    if intent == "rank_prediction":
        rank = extract_rank(query)

        if rank:
            print(f"🔢 Rank: {rank}")

            # Get matching cutoffs from Firebase
            cutoffs = firebase_service.get_cutoffs_by_rank(rank)

            if cutoffs:
                predictions = predict_branches(rank, cutoffs)
                context = format_predictions_for_gemini(predictions, rank)

                # Generate response (Gemini API)
                answer = generate_response(query, context, "rank_prediction")

                return {
                    "answer": answer,
                    "intent": "rank_prediction",
                    "confidence": confidence,
                    "rank_prediction": {
                        "rank": rank,
                        "predictions": predictions[:5]
                    },
                    "timestamp": datetime.utcnow().isoformat()
                }
            else:
                answer = f"With rank {rank}, I couldn't find predictions. Contact VIT admissions."
                return {
                    "answer": answer,
                    "intent": "rank_prediction",
                    "confidence": confidence,
                    "rank_prediction": {"rank": rank, "predictions": []},
                    "timestamp": datetime.utcnow().isoformat()
                }

    elif intent == "cutoff":
        # Generate query embedding (LOCAL - no API call)
        query_embedding = generate_query_embedding(query)
        print("🔍 Vector search on cutoffs (Sentence Transformers - LOCAL)...")

        # Vector search (LOCAL computation)
        cutoff_results = firebase_service.vector_search_cutoffs(query_embedding, top_k=5)

        if cutoff_results:
            print(f"✅ Found {len(cutoff_results)} cutoffs (scores: {[f'{r['score']:.3f}' for r in cutoff_results[:3]]})")

            context = "\n\n".join([doc["answer"] for doc in cutoff_results[:3]])

            # Generate response (Gemini API)
            answer = generate_response(query, context, "cutoff")

            return {
                "answer": answer,
                "intent": "cutoff",
                "confidence": confidence,
                "sources": [{"branch": doc["branch"], "campus": doc["campus"]} for doc in cutoff_results[:3]],
                "timestamp": datetime.utcnow().isoformat()
            }

    elif intent == "faq":
        # Generate query embedding (LOCAL - no API call)
        query_embedding = generate_query_embedding(query)
        print("🔍 Vector search on FAQs (Sentence Transformers - LOCAL)...")

        # Vector search (LOCAL computation)
        faq_results = firebase_service.vector_search_faqs(query_embedding, top_k=3)

        if faq_results:
            print(f"✅ Found {len(faq_results)} FAQs (scores: {[f'{r['score']:.3f}' for r in faq_results]})")

            context = "\n\n".join([
                f"Q: {doc['question']}\nA: {doc['answer']}"
                for doc in faq_results
            ])

            # Generate response (Gemini API)
            answer = generate_response(query, context, "faq")

            return {
                "answer": answer,
                "intent": "faq",
                "confidence": confidence,
                "sources": [{"question": doc["question"], "category": doc["category"]} for doc in faq_results],
                "timestamp": datetime.utcnow().isoformat()
            }

    # Default response
    answer = "Ask me about VIT cutoffs, hostels, FFCS, clubs, or provide your rank!"
    return {
        "answer": answer,
        "intent": intent,
        "confidence": confidence,
        "timestamp": datetime.utcnow().isoformat()
    }

print("✅ Query handler ready!")
print("\n" + "="*60)
print("✅ CORE SETUP COMPLETE!")
print("="*60)
print("💡 Sentence Transformers handles all embeddings (LOCAL)")
print("💡 Gemini only for intent + response generation")
print("="*60)
print("\n📌 Next: Run Cell 13 to load sample data")

# ===========================
# CELL 13: Sample Data
# ===========================
print("📚 Preparing sample data...")

SAMPLE_FAQS = [
    {
        "question": "What is FFCS in VIT?",
        "answer": "FFCS (Fully Flexible Credit System) is VIT's unique system that allows students to choose their own courses, faculty, and timetable. You can pick classes based on your interests, preferred professors, and schedule convenience.",
        "category": "Academics"
    },
    {
        "question": "How are the hostel facilities at VIT?",
        "answer": "VIT hostels are well-maintained with different blocks for boys and girls. Each room accommodates 2-3 students with beds, study tables, cupboards, and 24/7 Wi-Fi. Hostels have common rooms, mess facilities, laundry, and security.",
        "category": "Hostel"
    },
    {
        "question": "What clubs and chapters are available at VIT?",
        "answer": "VIT has 100+ active clubs including technical (robotics, coding, AI), cultural (dance, music, drama), sports clubs, and social service chapters. Popular ones include IEEE, CSI, SAE, Team Robocon, Dance Club, and NSS.",
        "category": "Campus Life"
    },
    {
        "question": "What is the admission process for VIT?",
        "answer": "VIT admission is based on VITEEE. After the exam, ranks are declared. Online counselling is conducted where students select branches and campuses based on rank. Seat allotment happens in multiple rounds.",
        "category": "Admissions"
    },
    {
        "question": "What are the different VIT campuses?",
        "answer": "VIT has four campuses: VIT Vellore (main), VIT Chennai (Vandalur), VIT Bhopal (MP), and VIT-AP (Amaravati, AP). Each offers various B.Tech programs.",
        "category": "Campus"
    },
    {
        "question": "What is the fee structure at VIT?",
        "answer": "VIT has category-based fees. Category 1 is ₹1.98-2.5 lakhs/year, Category 2 is ~₹3.5 lakhs, Category 3 is ~₹4.5 lakhs. Category is assigned during counselling based on rank and branch. Hostel fees are separate.",
        "category": "Fees"
    },
    {
        "question": "Are there placement opportunities at VIT?",
        "answer": "VIT has excellent placements with 800+ companies visiting annually including Google, Microsoft, Amazon. Average package is 7-9 LPA, highest packages cross 40+ LPA. The placement cell provides training and coaching.",
        "category": "Placements"
    },
    {
        "question": "Can I change my branch after joining VIT?",
        "answer": "Yes, VIT allows branch change after first year based on CGPA. You need to maintain high CGPA (usually 9.0+) and apply during the specified window. However, seats are limited.",
        "category": "Academics"
    },
    {
        "question": "What is the attendance policy at VIT?",
        "answer": "VIT has a strict 75% attendance policy. If attendance falls below 75%, students may not be allowed to write exams. Genuine medical emergencies with documentation are considered.",
        "category": "Academics"
    },
    {
        "question": "Is VIT strict about discipline?",
        "answer": "VIT maintains professional discipline focusing on academics and safety. There are rules about hostel timings and attendance. However, students have freedom for club activities and events.",
        "category": "Campus Life"
    }
]

SAMPLE_CUTOFFS = [
    {"campus": "VIT Vellore", "branch": "Computer Science and Engineering (CSE)", "category": "Category 1", "rank_range": [1, 4000], "answer": "CSE at VIT Vellore under Category 1 typically closes around rank 4000. Annual fees are around ₹1.98 lakhs."},
    {"campus": "VIT Vellore", "branch": "Computer Science and Engineering (CSE)", "category": "Category 2", "rank_range": [4001, 12000], "answer": "CSE at VIT Vellore under Category 2 accepts ranks from 4001 to around 12000. Annual fees are approximately ₹3.5 lakhs."},
    {"campus": "VIT Vellore", "branch": "Computer Science and Engineering (CSE)", "category": "Category 3", "rank_range": [12001, 22000], "answer": "CSE at VIT Vellore under Category 3 accepts ranks from 12001 to around 22000. Annual fees are approximately ₹4.5 lakhs."},
    {"campus": "VIT Vellore", "branch": "Electronics and Communication Engineering (ECE)", "category": "Category 1", "rank_range": [1, 8000], "answer": "ECE at VIT Vellore under Category 1 typically closes around rank 8000 with fees around ₹1.98 lakhs per year."},
    {"campus": "VIT Vellore", "branch": "Electronics and Communication Engineering (ECE)", "category": "Category 2", "rank_range": [8001, 20000], "answer": "ECE at VIT Vellore under Category 2 accepts ranks from 8001 to around 20000 with fees around ₹3.5 lakhs per year."},
    {"campus": "VIT Vellore", "branch": "Information Technology (IT)", "category": "Category 1", "rank_range": [1, 6000], "answer": "IT at VIT Vellore under Category 1 typically closes around rank 6000."},
    {"campus": "VIT Vellore", "branch": "Information Technology (IT)", "category": "Category 2", "rank_range": [6001, 15000], "answer": "IT at VIT Vellore under Category 2 accepts ranks from 6001 to around 15000."},
    {"campus": "VIT Chennai", "branch": "Computer Science and Engineering (CSE)", "category": "Category 1", "rank_range": [1, 8000], "answer": "CSE at VIT Chennai under Category 1 typically closes around rank 8000."},
    {"campus": "VIT Chennai", "branch": "Computer Science and Engineering (CSE)", "category": "Category 2", "rank_range": [8001, 25000], "answer": "CSE at VIT Chennai under Category 2 accepts ranks from 8001 to around 25000."},
    {"campus": "VIT Vellore", "branch": "Mechanical Engineering", "category": "Category 1", "rank_range": [1, 15000], "answer": "Mechanical Engineering at VIT Vellore under Category 1 accepts ranks up to 15000."},
    {"campus": "VIT Vellore", "branch": "Mechanical Engineering", "category": "Category 2", "rank_range": [15001, 35000], "answer": "Mechanical Engineering at VIT Vellore under Category 2 accepts ranks from 15001 to 35000."},
    {"campus": "VIT Vellore", "branch": "CSE with Specialization in AI & ML", "category": "Category 2", "rank_range": [1, 10000], "answer": "CSE with AI & ML specialization at VIT Vellore is highly sought after, with Category 2 closing around rank 10000."},
    {"campus": "VIT Vellore", "branch": "CSE with Specialization in AI & ML", "category": "Category 3", "rank_range": [10001, 20000], "answer": "CSE with AI & ML at VIT Vellore Category 3 accepts ranks from 10001 to 20000."},
    {"campus": "VIT Bhopal", "branch": "Computer Science and Engineering (CSE)", "category": "Category 1", "rank_range": [1, 30000], "answer": "CSE at VIT Bhopal under Category 1 is more accessible with cutoffs around rank 30000."},
    {"campus": "VIT-AP Amaravati", "branch": "Computer Science and Engineering (CSE)", "category": "Category 1", "rank_range": [1, 35000], "answer": "CSE at VIT-AP Amaravati under Category 1 accepts ranks up to 35000."}
]

print(f"✅ Sample data prepared!")
print(f"   📊 {len(SAMPLE_FAQS)} FAQs")
print(f"   📊 {len(SAMPLE_CUTOFFS)} Cutoff records")
print("📌 Next: Run Cell 14 to initialize database")

# ===========================
# CELL 14: Initialize Database
# ===========================
print("🗄 Initializing Firebase database with sample data...")

async def initialize_database():
    """Initialize Firebase with sample FAQs and cutoffs"""

    print("\n" + "="*60)
    print("📚 ADDING FAQs TO FIREBASE")
    print("="*60)

    faq_count = 0

    # Generate all FAQ embeddings at once (efficient batch processing)
    # This uses Sentence Transformers locally - NO API CALLS
    faq_questions = [faq["question"] for faq in SAMPLE_FAQS]
    print(f"⏳ Generating {len(faq_questions)} embeddings locally...")
    faq_embeddings = generate_batch_embeddings(faq_questions)
    print("✅ Embeddings generated!")

    # Add FAQs to Firebase
    for i, faq in enumerate(SAMPLE_FAQS):
        try:
            faq_doc = {
                **faq,
                "embedding": faq_embeddings[i],
                "created_at": datetime.utcnow().isoformat()
            }

            doc_id = firebase_service.add_faq(faq_doc)
            if doc_id:
                faq_count += 1
                print(f"  ✓ [{faq_count}/{len(SAMPLE_FAQS)}] {faq['question'][:50]}...")
        except Exception as e:
            print(f"  ✗ Failed: {e}")

    print(f"\n✅ Added {faq_count} FAQs to Firebase")

    print("\n" + "="*60)
    print("🎯 ADDING CUTOFFS TO FIREBASE")
    print("="*60)

    cutoff_count = 0

    # Generate cutoff embeddings in batch
    cutoff_texts = [f"{c['branch']} {c['campus']} {c['category']}" for c in SAMPLE_CUTOFFS]
    print(f"⏳ Generating {len(cutoff_texts)} embeddings locally...")
    cutoff_embeddings = generate_batch_embeddings(cutoff_texts)
    print("✅ Embeddings generated!")

    # Add cutoffs to Firebase
    for i, cutoff in enumerate(SAMPLE_CUTOFFS):
        try:
            cutoff_doc = {
                **cutoff,
                "embedding": cutoff_embeddings[i],
                "created_at": datetime.utcnow().isoformat()
            }

            doc_id = firebase_service.add_cutoff(cutoff_doc)
            if doc_id:
                cutoff_count += 1
                print(f"  ✓ [{cutoff_count}/{len(SAMPLE_CUTOFFS)}] {cutoff['branch'][:35]} - {cutoff['campus']}")
        except Exception as e:
            print(f"  ✗ Failed: {e}")

    print(f"\n✅ Added {cutoff_count} cutoff records to Firebase")

    print("\n" + "="*60)
    print("🎉 DATABASE INITIALIZATION COMPLETE!")
    print("="*60)
    print(f"   📊 Total FAQs: {faq_count}")
    print(f"   📊 Total Cutoffs: {cutoff_count}")
    print(f"   💰 API Costs: $0.00 (all embeddings generated locally)")
    print("="*60)

# Run initialization
print("⏳ Starting database initialization...")
await initialize_database()

print("\n📌 Next: Run Cell 15 to set up FastAPI server")

# ===========================
# CELL 15: FastAPI Setup
# ===========================
print("🚀 Setting up FastAPI server...")

# Initialize FastAPI
app = FastAPI(
    title="VIT Admission AI Chatbot",
    description="Smart chatbot powered by Gemini AI, Firebase & Sentence Transformers",
    version="2.0.0"
)

# CORS middleware
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Request/Response Models
class QueryRequest(BaseModel):
    query: str
    user_id: Optional[str] = None
    session_id: Optional[str] = None

class QueryResponse(BaseModel):
    answer: str
    intent: str
    confidence: float
    sources: Optional[List[Dict]] = None
    rank_prediction: Optional[Dict] = None
    timestamp: str

class FAQInput(BaseModel):
    question: str
    answer: str
    category: Optional[str] = "General"

class CutoffInput(BaseModel):
    campus: str
    branch: str
    category: str
    rank_range: List[int]
    answer: str

# Root endpoint
@app.get("/")
async def root():
    return {
        "status": "active",
        "service": "VIT Admission AI Chatbot",
        "version": "2.0.0",
        "embedding_model": EMBEDDING_MODEL_NAME,
        "embedding_dimension": embedding_dimension,
        "features": [
            "Local Embeddings (Sentence Transformers)",
            "Vector Search with Firebase",
            "Gemini AI for Intent & Responses",
            "Rank Prediction",
            "Zero-cost Embeddings"
        ]
    }

# Health check
@app.get("/health")
async def health_check():
    return {
        "status": "healthy",
        "firebase": "connected",
        "gemini": "active",
        "embedding_model": EMBEDDING_MODEL_NAME,
        "embedding_dimension": embedding_dimension,
        "timestamp": datetime.utcnow().isoformat()
    }

# Main chatbot endpoint
@app.post("/ask", response_model=QueryResponse)
async def ask_question(request: QueryRequest):
    """
    Main endpoint to handle user queries

    Flow:
    1. Intent Classification (Gemini API)
    2. Query Embedding (Local - Sentence Transformers)
    3. Vector Search (Local computation)
    4. Response Generation (Gemini API)
    """
    try:
        result = await process_query(request.query, request.user_id)

        # Log to Firebase
        firebase_service.log_query({
            "query": request.query,
            "user_id": request.user_id,
            "session_id": request.session_id,
            "intent": result["intent"],
            "confidence": result["confidence"]
        })

        return QueryResponse(**result)

    except Exception as e:
        print(f"Error processing query: {e}")
        raise HTTPException(status_code=500, detail=str(e))

# Add FAQ endpoint
@app.post("/admin/faq")
async def add_faq(faq: FAQInput):
    """Add new FAQ to Firebase (embedding generated locally)"""
    try:
        # Generate embedding locally (no API call)
        embedding = generate_embedding(faq.question)

        faq_doc = {
            "question": faq.question,
            "answer": faq.answer,
            "category": faq.category,
            "embedding": embedding,
            "created_at": datetime.utcnow().isoformat()
        }

        doc_id = firebase_service.add_faq(faq_doc)

        if doc_id:
            return {"status": "success", "id": doc_id, "message": "FAQ added successfully"}
        else:
            raise HTTPException(status_code=500, detail="Failed to add FAQ")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

# Add cutoff endpoint
@app.post("/admin/cutoff")
async def add_cutoff(cutoff: CutoffInput):
    """Add new cutoff data to Firebase (embedding generated locally)"""
    try:
        # Generate embedding locally (no API call)
        embedding_text = f"{cutoff.branch} {cutoff.campus} {cutoff.category}"
        embedding = generate_embedding(embedding_text)

        cutoff_doc = {
            "campus": cutoff.campus,
            "branch": cutoff.branch,
            "category": cutoff.category,
            "rank_range": cutoff.rank_range,
            "answer": cutoff.answer,
            "embedding": embedding,
            "created_at": datetime.utcnow().isoformat()
        }

        doc_id = firebase_service.add_cutoff(cutoff_doc)

        if doc_id:
            return {"status": "success", "id": doc_id, "message": "Cutoff added successfully"}
        else:
            raise HTTPException(status_code=500, detail="Failed to add cutoff")

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

print("✅ FastAPI server configured!")
print("📌 Next: Run Cell 16 to start the server with ngrok")

# ===========================
# CELL 16: Start Server with ngrok
# ===========================
print("\n🌐 Starting server with ngrok tunnel...")

# Set ngrok auth token
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Start ngrok tunnel
public_url = ngrok.connect(8000)

print("\n" + "="*70)
print("🎉 SERVER IS RUNNING!")
print("="*70)
print(f"🔡 Public URL: {public_url}")
print(f"📖 API Docs: {public_url}/docs")
print(f"📖 ReDoc: {public_url}/redoc")
print("="*70)
print("\n💡 EMBEDDING INFO:")
print(f"   Model: {EMBEDDING_MODEL_NAME}")
print(f"   Dimension: {embedding_dimension}")
print(f"   Cost: $0.00 (local generation)")
print("\n💡 GEMINI USAGE:")
print("   • Intent classification (1 call/query)")
print("   • Response generation (1 call/query)")
print("   • Reduced API usage by ~60-70%")
print("="*70)

# Run the FastAPI server
from threading import Thread

def run_server():
    uvicorn.run(app, host="0.0.0.0", port=8000, log_level="info")

# Start server in background thread
server_thread = Thread(target=run_server, daemon=True)
server_thread.start()

print("\n✅ Server started successfully!")
print("\n💡 Keep this notebook open to keep the server alive!")
print("💡 Use the public URL to access your API from anywhere!")

print("\n📋 AVAILABLE ENDPOINTS:")
print(f"   GET  {public_url}/")
print(f"   GET  {public_url}/health")
print(f"   POST {public_url}/ask")
print(f"   POST {public_url}/admin/faq")
print(f"   POST {public_url}/admin/cutoff")
print(f"\n   📖 Interactive API Docs: {public_url}/docs")

print("\n📌 Next: Run Cell 17 to test the chatbot")

# ===========================
# CELL 17: Test the Chatbot
# ===========================
print("🧪 Testing the chatbot with sample queries...\n")

async def test_chatbot():
    """Test the chatbot with various queries"""

    test_queries = [
        {
            "name": "FAQ Query - FFCS",
            "query": "What is FFCS?"
        },
        {
            "name": "FAQ Query - Hostels",
            "query": "Tell me about hostel facilities at VIT"
        },
        {
            "name": "Rank Prediction - 12500",
            "query": "I got 12500 rank in VITEEE. Can I get CSE at Vellore?"
        },
        {
            "name": "Rank Prediction - 8000",
            "query": "My VITEEE rank is 8000. What are my options?"
        },
        {
            "name": "Cutoff Query",
            "query": "What is the cutoff for ECE at VIT Vellore?"
        },
        {
            "name": "Clubs Query",
            "query": "What clubs are available at VIT?"
        }
    ]

    for i, test in enumerate(test_queries, 1):
        print("\n" + "="*70)
        print(f"TEST {i}/{len(test_queries)}: {test['name']}")
        print("="*70)
        print(f"❓ Query: {test['query']}")
        print("-"*70)

        try:
            result = await process_query(test['query'])

            print(f"\n🎯 Intent: {result['intent']}")
            print(f"📊 Confidence: {result['confidence']:.2f}")
            print(f"\n💬 Response:")
            print(f"   {result['answer']}")

            if 'rank_prediction' in result and result['rank_prediction']:
                rank_pred = result['rank_prediction']
                if 'predictions' in rank_pred and rank_pred['predictions']:
                    print(f"\n🎓 Top Predictions:")
                    for pred in rank_pred['predictions'][:3]:
                        print(f"   • {pred['branch']} - {pred['campus']} ({pred['confidence']})")

            if 'sources' in result and result['sources']:
                print(f"\n📚 Sources: {len(result['sources'])} documents")

        except Exception as e:
            print(f"❌ Error: {e}")

        time.sleep(1.5)

    print("\n" + "="*70)
    print("✅ ALL TESTS COMPLETED!")
    print("="*70)
    print("\n💰 COST ANALYSIS:")
    print(f"   Gemini API calls: ~{len(test_queries) * 2} (intent + response)")
    print(f"   Embedding API calls: 0 (all local)")
    print(f"   Estimated savings: ~70% compared to Gemini embeddings")

# Run tests
await test_chatbot()

print("\n📌 Optional: Run Cell 18 for interactive chat mode")

# ===========================
# CELL 18: Interactive Chat Mode
# ===========================
print("\n" + "="*70)
print("🎮 INTERACTIVE CHATBOT MODE")
print("="*70)
print("Type your questions below. Type 'exit', 'quit', or 'stop' to end.\n")

async def interactive_chat():
    """Interactive chat mode for testing"""

    query_count = 0

    while True:
        try:
            query = input("\n👤 You: ").strip()

            if query.lower() in ['exit', 'quit', 'stop']:
                print("\n" + "="*70)
                print("👋 Goodbye! Thanks for chatting!")
                print("="*70)
                print(f"\n📊 Session Stats:")
                print(f"   Queries processed: {query_count}")
                print(f"   Gemini API calls: ~{query_count * 2}")
                print(f"   Embedding API calls: 0 (all local)")
                print("="*70)
                break

            if not query:
                continue

            print("\n🤖 Processing...")

            result = await process_query(query)
            query_count += 1

            print(f"\n🤖 VIT Bot: {result['answer']}")
            print(f"\n   📊 Intent: {result['intent']} | Confidence: {result['confidence']:.2f}")

            if 'sources' in result and result['sources']:
                print(f"   📚 Sources used: {len(result['sources'])}")

        except KeyboardInterrupt:
            print("\n\n" + "="*70)
            print("👋 Chat session ended (Keyboard Interrupt)")
            print("="*70)
            break
        except Exception as e:
            print(f"\n❌ Error: {e}")

# Start interactive chat
await interactive_chat()

print("\n✅ Interactive chat session completed!")
print("📌 Optional: Run Cell 19 for API testing with HTTP requests")

# ===========================
# DIAGNOSTIC CELL - Check API Issues
# ===========================
print("🔍 Running diagnostics...\n")

# Test 1: Check Gemini API Key
print("1️⃣ Testing Gemini API...")
try:
    test_response = gemini_model.generate_content("Say 'Hello'")
    print(f"   ✅ Gemini API is working!")
    print(f"   Response: {test_response.text[:50]}")
except Exception as e:
    print(f"   ❌ Gemini API FAILED!")
    print(f"   Error: {str(e)}")
    print(f"\n   💡 Solutions:")
    print(f"      • Check your API key in Cell 3")
    print(f"      • Get new key: https://makersuite.google.com/app/apikey")
    print(f"      • Check quota: https://makersuite.google.com/app/apikey")

print("\n" + "="*70)

# Test 2: Check Sentence Transformers
print("2️⃣ Testing Sentence Transformers...")
try:
    test_embedding = generate_embedding("test")
    print(f"   ✅ Sentence Transformers working!")
    print(f"   Embedding dimension: {len(test_embedding)}")
except Exception as e:
    print(f"   ❌ Sentence Transformers FAILED!")
    print(f"   Error: {str(e)}")

print("\n" + "="*70)

# Test 3: Check Firebase Connection
print("3️⃣ Testing Firebase...")
try:
    # Try to read from Firebase
    test_docs = list(firebase_service.faqs_collection.limit(1).stream())
    if test_docs:
        print(f"   ✅ Firebase is connected!")
        print(f"   Found {len(test_docs)} document(s)")
    else:
        print(f"   ⚠️ Firebase connected but no data found")
        print(f"   💡 Run Cell 14 to initialize database")
except Exception as e:
    print(f"   ❌ Firebase FAILED!")
    print(f"   Error: {str(e)}")

print("\n" + "="*70)

# Test 4: Full Query Test
print("4️⃣ Testing Full Query Flow...")
try:
    test_query = "What is FFCS?"
    print(f"   Query: {test_query}")

    # Test intent classification
    intent_result = classify_intent(test_query)
    print(f"   Intent: {intent_result['intent']}")
    print(f"   Confidence: {intent_result['confidence']}")

    # Test embedding generation
    query_emb = generate_query_embedding(test_query)
    print(f"   Embedding generated: {len(query_emb)} dimensions")

    # Test vector search
    results = firebase_service.vector_search_faqs(query_emb, top_k=1)
    print(f"   Vector search results: {len(results)}")

    if results:
        print(f"   Top match: {results[0]['question'][:50]}...")
        print(f"   Score: {results[0]['score']:.3f}")

    print(f"   ✅ Full flow working!")

except Exception as e:
    print(f"   ❌ Query flow FAILED!")
    print(f"   Error: {str(e)}")
    import traceback
    print(f"\n   Full error:")
    traceback.print_exc()

print("\n" + "="*70)
print("🏁 DIAGNOSTIC COMPLETE")
print("="*70)

# Provide recommendations
print("\n💡 RECOMMENDATIONS:")
print("   1. If Gemini API failed:")
print("      • Update GEMINI_API_KEY in Cell 3")
print("      • Check quota at: https://makersuite.google.com/app/apikey")
print("      • Try using a different model: 'gemini-1.5-flash'")
print("\n   2. If Firebase failed:")
print("      • Re-upload firebase credentials JSON")
print("      • Run Cell 4 again")
print("\n   3. If no data found:")
print("      • Run Cell 14 to initialize database")
print("="*70)